base_url = "https://pbzweihander.github.io"
description = "@pbzweihander"
compile_sass = false
minify_html = true
generate_feed = true
default_language = "ko_KR"

theme = "anemone"

[markdown]
render_emoji = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
twitter_card = true

favicon = "favicon.ico"

header_nav = [
    { url = "/", name_ko_KR = "/home/" },
    { url = "/post", name_ko_KR = "/posts/" },
]
