base_url = "https://pbzweihander.github.io"

title = "Thinking With Rust"
description = "@pbzweihander"

sort_by = "date"

compile_sass = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = []
