base_url = "https://pbzweihander.github.io"
compile_sass = false
minify_html = true
generate_feed = true
default_language = "ko_KR"

theme = "no-style-please"

taxonomies = [{ name = "categories" }, { name = "tags" }]

[markdown]
render_emoji = true
external_links_target_blank = true
highlight_code = true

[extra]
twitter_card = true

favicon = "favicon.ico"

header_nav = [
    { name = "~home", url = "/" },
    { name = "/posts", url = "/post/" },
    { name = "#tags", url = "/tags/" },
    { name = "=feed", url = "/atom.xml" },
]
